In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\Benks\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
modern_df = pd.read_csv('.\Datasets\modern_ai.csv')
pre_df2 = pd.read_csv('.\Datasets\pre_ai.csv')

print("Modern AI Dataset Statistics:")
print(modern_df.describe())
print("\nPre AI Dataset Statistics:")
print(pre_df2.describe())

Modern AI Dataset Statistics:
                 id  conversation_id       timezone  replies_count  \
count  8.930760e+05     8.930760e+05  893076.000000  893076.000000
mean   1.040813e+18     1.040717e+18    -407.503057       0.108286
std    1.496239e+17     1.496439e+17      26.344081       3.580560
min    8.246196e+17     6.059109e+09    -500.000000       0.000000
25%    9.033985e+17     9.033854e+17    -400.000000       0.000000
50%    1.012776e+18     1.012763e+18    -400.000000       0.000000
75%    1.156422e+18     1.156399e+18    -400.000000       0.000000
max    1.417273e+18     1.417273e+18    -400.000000    1881.000000

       retweets_count    likes_count          video
count   893076.000000  893076.000000  893076.000000
mean         1.678344       2.393616       0.313502
std         84.509796     248.674498       0.463917
min          0.000000       0.000000       0.000000
25%          0.000000       0.000000       0.000000
50%          0.000000       0.000000       0.000000
75%          1.000000       1.000000       1.000000
max      78672.000000  231879.000000       1.000000

Pre AI Dataset Statistics:
         Unnamed: 0      Tweet Id
count  56221.000000  5.622100e+04
mean   28110.000000  1.628960e+18
std    16229.749079  1.689126e+16
min        0.000000  1.517066e+18
25%    14055.000000  1.620891e+18
50%    28110.000000  1.633258e+18
75%    42165.000000  1.641162e+18
max    56220.000000  1.648800e+18

In [6]:
modern_df.head()

,id,conversation_id,created_at,date,time,timezone,tweet,language,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,retweet,quote_url,video,thumbnail
0,8.265808e+17,8.265808e+17,2017-01-31 18:59:44 EST,2017-01-31,18:59:44,-400,What topic could spark human dialogue on AI? A...,en,['https://blog.hubspot.com/marketing/artificia...,[],0,0,0,[],[],False,NaN,0,NaN
1,8.265807e+17,8.265807e+17,2017-01-31 18:59:35 EST,2017-01-31,18:59:35,-400,I think #ArtificialIntelligence will augment h...,en,['http://bit.ly/2bWb1ly'],[],0,4,1,"['artificialintelligence', 'ai', 'chasmwaxing']",[],False,NaN,0,NaN
2,8.265806e+17,8.265806e+17,2017-01-31 18:59:14 EST,2017-01-31,18:59:14,-400,What Managers Need to Know About Artificial In...,en,['http://mitsmr.com/2klQ17D'],[],0,1,0,[],[],False,NaN,0,NaN
3,8.265806e+17,8.265806e+17,2017-01-31 18:59:01 EST,2017-01-31,18:59:01,-400,4 ways Artificial Intelligence changes the gam...,en,['http://bit.ly/2koUCIB'],[],0,0,0,['thenextweb'],[],False,NaN,0,NaN
4,8.265806e+17,8.265806e+17,2017-01-31 18:59:01 EST,2017-01-31,18:59:01,-400,Artificial Intelligence can Shape the Future o...,en,['https://www.youtube.com/watch?v=NQefTsrSjJY'],[],0,0,0,[],[],False,NaN,0,NaN